# import smtplib
# from email.mime.text import MIMEText

# def send_email(sender, password, receiver, subject, body):
#     msg = MIMEText(body)
#     msg["Subject"] = subject
#     msg["From"] = sender
#     msg["To"] = receiver

#     with smtplib.SMTP("smtp.gmail.com", 587) as server:
#         server.starttls()
#         server.login(sender, password)
#         server.send_message(msg)

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

def send_email(sender, password, receiver, subject, decision_payload):
    """
    decision_payload: dict returned by CampaignEngine.evaluate()
    """

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = receiver

    html_body = f"""
    <html>
      <body style="font-family: Arial, sans-serif;">
        <h2>🌧 Weather Operations Alert – {decision_payload['city']}</h2>

        <p><b>Decision:</b> {decision_payload['decision']}</p>

        <hr>

        <h3>📊 Weather Summary</h3>
        <ul>
          <li><b>Average Precipitation:</b> {decision_payload['avg_precip']} mm/hr</li>
          <li><b>Bad Weather Hours:</b> {decision_payload['bad_weather_pct']}%</li>
        </ul>

        <h3>⚙ Operational Details</h3>
        <ul>
          <li><b>Opt Type:</b> {decision_payload['opt_type']}</li>
          <li><b>Cohort Size:</b> {decision_payload['cohort_size']}</li>
          <li><b>Communications Enabled:</b> {"Yes" if decision_payload['comms_on'] else "No"}</li>
        </ul>

        <h3>🛡 Safety Guidance</h3>
        <p>
          Courier safety is prioritized. Please follow standard safety
          guidelines during adverse weather conditions.
        </p>

        <hr>
        <p style="font-size: 12px; color: gray;">
          This is an automated message generated by the Weather Intelligence System.
        </p>
      </body>
    </html>
    """

    msg.attach(MIMEText(html_body, "html"))

    with smtplib.SMTP("smtp.gmail.com", 587) as server:
        server.starttls()
        server.login(sender, password)
        server.send_message(msg)

